### ISSUE TITLE
main page - search bar

### ISSUE THREAD

**Issue by LuizaAK** [dwayned84/formy#47] opened 2021-03-31 05:14 UTC
1. Mozilla v. 50
2. software 1.1.1
3. go to www.google.com
3. The left border of the search bar is missing
![main page (2)_LI](https://user-images.githubusercontent.com/81632625/113096021-56e95480-9216-11eb-8a17-c565310c850f.jpg)

**Comment by dwayned84** [comment] 2021-03-31 05:24
Please mention in the title of the ticket which part of the software is related to the issue -> Main page search field issue. 
FYI, This thing that is missing is called border. 
Don't forget to include steps : Go to www.google.com. Developers need to know the url of the page where the issue is.

**Comment by dwayned84** [comment] 2021-03-31 14:07
Great. I'm closing the ticket.

**Closed as completed by dwayned84** 2021-03-31 14:07 UTC
